// templates-registry.test.ts pins the four shipping templates' identity
// and the link between the runtime registry and the generated bytes.
// A drifted registry (e.g. someone renamed a template id in the picker
// metadata but didn't re-run the Go generator) would surface as a
// hidden failure at runtime — the picker would render a card but
// clicking it would throw "Unknown text template id". This test
// catches that drift at vitest time instead.

import { existsSync, statSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import {
    getTemplate,
    getTemplateBase64,
    TEXT_TEMPLATES,
    type TemplateId,
} from '../tinycld/text/lib/templates/index'
import { GENERATED_TEMPLATE_BYTES } from '../tinycld/text/lib/templates/templates.generated'

const PACKAGE_ROOT = resolve(__dirname, '..')

const EXPECTED_IDS: ReadonlyArray<TemplateId> = ['blank', 'letter', 'resume', 'report']

describe('text templates registry', () => {
    it('ships exactly the four expected templates in stable order', () => {
        expect(TEXT_TEMPLATES.map(t => t.id)).toEqual(EXPECTED_IDS)
    })

    it('each entry has required, non-empty fields', () => {
        for (const tpl of TEXT_TEMPLATES) {
            expect(typeof tpl.id).toBe('string')
            expect(tpl.id.length).toBeGreaterThan(0)
            expect(typeof tpl.name).toBe('string')
            expect(tpl.name.length).toBeGreaterThan(0)
            expect(typeof tpl.description).toBe('string')
            expect(tpl.description.length).toBeGreaterThan(0)
            // fileName drives the user-visible drive item name; must end
            // with .docx so the opener actions match it.
            expect(tpl.fileName.toLowerCase().endsWith('.docx')).toBe(true)
        }
    })

    it('every registry entry has bytes in the generated bundle', () => {
        const generatedIds = new Set(GENERATED_TEMPLATE_BYTES.map(e => e.id))
        for (const tpl of TEXT_TEMPLATES) {
            expect(generatedIds.has(tpl.id)).toBe(true)
        }
    })

    it('every generated-bytes entry is also in the registry (no stale ids)', () => {
        const registryIds = new Set(TEXT_TEMPLATES.map(t => t.id))
        for (const entry of GENERATED_TEMPLATE_BYTES) {
            expect(registryIds.has(entry.id as TemplateId)).toBe(true)
        }
    })

    it('every template has a committed .docx file on disk', () => {
        for (const tpl of TEXT_TEMPLATES) {
            const p = join(PACKAGE_ROOT, 'tinycld', 'text', 'assets', 'templates', `${tpl.id}.docx`)
            expect(existsSync(p), `missing ${p}`).toBe(true)
            // Smallest valid docx is ~3KB (Content_Types + minimal
            // document.xml + rels). Anything smaller indicates a corrupted
            // generator output.
            expect(statSync(p).size).toBeGreaterThan(500)
        }
    })
})

describe('text templates lookups', () => {
    it('getTemplate returns the same entry by id', () => {
        for (const tpl of TEXT_TEMPLATES) {
            expect(getTemplate(tpl.id)).toBe(tpl)
        }
    })

    it('getTemplate throws on an unknown id', () => {
        expect(() => getTemplate('bogus' as TemplateId)).toThrow(/Unknown text template id/)
    })

    it('getTemplateBase64 returns a non-empty base64 string for each known id', () => {
        for (const tpl of TEXT_TEMPLATES) {
            const b64 = getTemplateBase64(tpl.id)
            expect(typeof b64).toBe('string')
            expect(b64.length).toBeGreaterThan(0)
            // Valid base64 alphabet only (allow newlines for safety even
            // though the generator emits one-line strings).
            expect(/^[A-Za-z0-9+/=\s]+$/.test(b64)).toBe(true)
        }
    })

    it('getTemplateBase64 throws on an unknown id', () => {
        expect(() => getTemplateBase64('bogus' as TemplateId)).toThrow(/Unknown text template id/)
    })
})
