// Static catalog of HyperFormula's built-in functions for the
// `calc:functions` help topic. Sourced from
// https://hyperformula.handsontable.com/guide/built-in-functions.html
// for HF 3.2.0. Refresh by re-running scripts/build-function-catalog
// when bumping the hyperformula dep — the docs page is the canonical
// source for descriptions and signatures.
//
// Keyed by category so the help-topic generator can emit a section per
// group. Function names match HyperFormula.getRegisteredFunctionNames
// ('enGB'). Functions documented but not registered in this version
// (TEXTJOIN, SEQUENCE, PERCENTILE*, QUARTILE*) are omitted; VERSION is
// registered but not documented and is described here directly.

export interface FunctionEntry {
    name: string
    syntax: string
    description: string
}

export interface FunctionCategory {
    title: string
    entries: FunctionEntry[]
}

export const FUNCTION_CATALOG: FunctionCategory[] = [
    {
        title: 'Math and trigonometry',
        entries: [
            { name: 'ABS', syntax: 'ABS(Number)', description: 'Returns the absolute value of a number.' },
            { name: 'ACOS', syntax: 'ACOS(Number)', description: 'Returns the inverse trigonometric cosine of a number.' },
            { name: 'ACOSH', syntax: 'ACOSH(Number)', description: 'Returns the inverse hyperbolic cosine of a number.' },
            { name: 'ACOT', syntax: 'ACOT(Number)', description: 'Returns the inverse trigonometric cotangent of a number.' },
            { name: 'ACOTH', syntax: 'ACOTH(Number)', description: 'Returns the inverse hyperbolic cotangent of a number.' },
            { name: 'ARABIC', syntax: 'ARABIC(String)', description: 'Converts a Roman numeral string into an Arabic number.' },
            { name: 'ASIN', syntax: 'ASIN(Number)', description: 'Returns the inverse trigonometric sine of a number.' },
            { name: 'ASINH', syntax: 'ASINH(Number)', description: 'Returns the inverse hyperbolic sine of a number.' },
            { name: 'ATAN', syntax: 'ATAN(Number)', description: 'Returns the inverse trigonometric tangent of a number.' },
            { name: 'ATAN2', syntax: 'ATAN2(NumberX, NumberY)', description: 'Returns the inverse trigonometric tangent of specified x and y coordinates.' },
            { name: 'ATANH', syntax: 'ATANH(Number)', description: 'Returns the inverse hyperbolic tangent of a number.' },
            { name: 'BASE', syntax: 'BASE(Number, Radix, [MinimumLength])', description: 'Converts a positive integer to text in a specified base.' },
            { name: 'CEILING', syntax: 'CEILING(Number, Significance)', description: 'Rounds a number up to the nearest multiple of Significance.' },
            { name: 'CEILING.MATH', syntax: 'CEILING.MATH(Number[, Significance[, Mode]])', description: 'Rounds a number up to the nearest multiple of Significance.' },
            { name: 'CEILING.PRECISE', syntax: 'CEILING.PRECISE(Number[, Significance])', description: 'Rounds a number up to the nearest multiple of Significance.' },
            { name: 'COMBIN', syntax: 'COMBIN(Number, Number)', description: 'Returns the number of combinations (without repetitions).' },
            { name: 'COMBINA', syntax: 'COMBINA(Number, Number)', description: 'Returns the number of combinations (with repetitions).' },
            { name: 'COS', syntax: 'COS(Number)', description: 'Returns the cosine of the given angle (in radians).' },
            { name: 'COSH', syntax: 'COSH(Number)', description: 'Returns the hyperbolic cosine of the given value.' },
            { name: 'COT', syntax: 'COT(Number)', description: 'Returns the cotangent of the given angle (in radians).' },
            { name: 'COTH', syntax: 'COTH(Number)', description: 'Returns the hyperbolic cotangent of the given value.' },
            { name: 'COUNTUNIQUE', syntax: 'COUNTUNIQUE(Value1, Value2, ...ValueN)', description: 'Counts the number of unique values in a list of specified values and ranges.' },
            { name: 'CSC', syntax: 'CSC(Number)', description: 'Returns the cosecant of the given angle (in radians).' },
            { name: 'CSCH', syntax: 'CSCH(Number)', description: 'Returns the hyperbolic cosecant of the given value.' },
            { name: 'DECIMAL', syntax: 'DECIMAL("Text", Radix)', description: 'Converts text in a given numeral system to a positive integer.' },
            { name: 'DEGREES', syntax: 'DEGREES(Number)', description: 'Converts radians into degrees.' },
            { name: 'EVEN', syntax: 'EVEN(Number)', description: 'Rounds positive numbers up to the next even integer, negative numbers down.' },
            { name: 'EXP', syntax: 'EXP(Number)', description: 'Returns constant e raised to the power of a number.' },
            { name: 'FACT', syntax: 'FACT(Number)', description: 'Returns the factorial of a number.' },
            { name: 'FACTDOUBLE', syntax: 'FACTDOUBLE(Number)', description: 'Returns the double factorial of a number.' },
            { name: 'FLOOR', syntax: 'FLOOR(Number, Significance)', description: 'Rounds a number down to the nearest multiple of Significance.' },
            { name: 'FLOOR.MATH', syntax: 'FLOOR.MATH(Number[, Significance[, Mode]])', description: 'Rounds a number down to the nearest multiple of Significance.' },
            { name: 'FLOOR.PRECISE', syntax: 'FLOOR.PRECISE(Number[, Significance])', description: 'Rounds a number down to the nearest multiple of Significance.' },
            { name: 'GCD', syntax: 'GCD(Number1, Number2, ...NumberN)', description: 'Computes the greatest common divisor of numbers.' },
            { name: 'INT', syntax: 'INT(Number)', description: 'Rounds a number down to the nearest integer.' },
            { name: 'ISO.CEILING', syntax: 'ISO.CEILING(Number[, Significance])', description: 'Rounds a number up to the nearest multiple of Significance.' },
            { name: 'LCM', syntax: 'LCM(Number1, Number2, ...NumberN)', description: 'Computes the least common multiple of numbers.' },
            { name: 'LN', syntax: 'LN(Number)', description: 'Returns the natural logarithm (base e) of a number.' },
            { name: 'LOG', syntax: 'LOG(Number, Base)', description: 'Returns the logarithm of a number to the specified base.' },
            { name: 'LOG10', syntax: 'LOG10(Number)', description: 'Returns the base-10 logarithm of a number.' },
            { name: 'MOD', syntax: 'MOD(Dividend, Divisor)', description: 'Returns the remainder when one integer is divided by another.' },
            { name: 'MROUND', syntax: 'MROUND(Number, Base)', description: 'Rounds a number to the nearest multiple of Base.' },
            { name: 'MULTINOMIAL', syntax: 'MULTINOMIAL(Number1, Number2, ...NumberN)', description: 'Returns the number of multiset combinations.' },
            { name: 'ODD', syntax: 'ODD(Number)', description: 'Rounds positive numbers up to the next odd integer, negative numbers down.' },
            { name: 'PI', syntax: 'PI()', description: 'Returns 3.14159265358979, the value of the mathematical constant pi.' },
            { name: 'POWER', syntax: 'POWER(Base, Exponent)', description: 'Returns a number raised to another number.' },
            { name: 'PRODUCT', syntax: 'PRODUCT(Number1, Number2, ...NumberN)', description: 'Returns the product of numbers.' },
            { name: 'QUOTIENT', syntax: 'QUOTIENT(Dividend, Divisor)', description: 'Returns the integer part of a division.' },
            { name: 'RADIANS', syntax: 'RADIANS(Number)', description: 'Converts degrees to radians.' },
            { name: 'RAND', syntax: 'RAND()', description: 'Returns a random number between 0 and 1.' },
            { name: 'RANDBETWEEN', syntax: 'RANDBETWEEN(LowerBound, UpperBound)', description: 'Returns a random integer between two numbers (inclusive).' },
            { name: 'ROMAN', syntax: 'ROMAN(Number[, Mode])', description: 'Converts a number to a Roman numeral.' },
            { name: 'ROUND', syntax: 'ROUND(Number, Count)', description: 'Rounds a number to a certain number of decimal places.' },
            { name: 'ROUNDDOWN', syntax: 'ROUNDDOWN(Number, Count)', description: 'Rounds a number down, toward zero, to a given precision.' },
            { name: 'ROUNDUP', syntax: 'ROUNDUP(Number, Count)', description: 'Rounds a number up, away from zero, to a given precision.' },
            { name: 'SEC', syntax: 'SEC(Number)', description: 'Returns the secant of the given angle (in radians).' },
            { name: 'SECH', syntax: 'SECH(Number)', description: 'Returns the hyperbolic secant of the given value.' },
            { name: 'SERIESSUM', syntax: 'SERIESSUM(X, N, M, Coefficients)', description: 'Evaluates a power series at a point.' },
            { name: 'SIN', syntax: 'SIN(Number)', description: 'Returns the sine of the given angle (in radians).' },
            { name: 'SINH', syntax: 'SINH(Number)', description: 'Returns the hyperbolic sine of the given value.' },
            { name: 'SIGN', syntax: 'SIGN(Number)', description: 'Returns the sign of a number (-1, 0, or 1).' },
            { name: 'SQRT', syntax: 'SQRT(Number)', description: 'Returns the positive square root of a number.' },
            { name: 'SQRTPI', syntax: 'SQRTPI(Number)', description: 'Returns the square root of a number multiplied by pi.' },
            { name: 'SUBTOTAL', syntax: 'SUBTOTAL(Function, Number1, Number2, ...NumberN)', description: 'Computes an aggregation using the function specified by the number.' },
            { name: 'SUM', syntax: 'SUM(Number1, Number2, ...NumberN)', description: 'Sums up the values of the specified cells.' },
            { name: 'SUMIF', syntax: 'SUMIF(Range, Criteria, SumRange)', description: 'Sums cells that meet a specified condition within a range.' },
            { name: 'SUMIFS', syntax: 'SUMIFS(SumRange, CriterionRange1, Criterion1 [, ...])', description: 'Sums cells meeting multiple condition sets within ranges.' },
            { name: 'SUMPRODUCT', syntax: 'SUMPRODUCT(Array1, Array2, ...ArrayN)', description: 'Multiplies corresponding elements in arrays and returns the sum.' },
            { name: 'SUMSQ', syntax: 'SUMSQ(Number1, Number2, ...NumberN)', description: 'Returns the sum of the squares of the arguments.' },
            { name: 'SUMX2MY2', syntax: 'SUMX2MY2(Range1, Range2)', description: 'Returns the sum of the differences of squares of paired values.' },
            { name: 'SUMX2PY2', syntax: 'SUMX2PY2(Range1, Range2)', description: 'Returns the sum of the sums of squares of paired values.' },
            { name: 'SUMXMY2', syntax: 'SUMXMY2(Range1, Range2)', description: 'Returns the sum of the squares of differences between paired values.' },
            { name: 'TAN', syntax: 'TAN(Number)', description: 'Returns the tangent of the given angle (in radians).' },
            { name: 'TANH', syntax: 'TANH(Number)', description: 'Returns the hyperbolic tangent of the given value.' },
            { name: 'TRUNC', syntax: 'TRUNC(Number, Count)', description: 'Truncates a number by removing decimal places.' },
        ],
    },
    {
        title: 'Logical',
        entries: [
            { name: 'AND', syntax: 'AND(LogicalValue1, LogicalValue2, ...LogicalValueN)', description: 'Returns TRUE if all arguments are TRUE.' },
            { name: 'FALSE', syntax: 'FALSE()', description: 'Returns the logical value FALSE.' },
            { name: 'IF', syntax: 'IF(Test, ThenValue, OtherwiseValue)', description: 'Returns one value if a test is TRUE, another if it is FALSE.' },
            { name: 'IFS', syntax: 'IFS(Condition1, Value1 [, Condition2, Value2 [, ...]])', description: 'Evaluates multiple logical tests and returns the value for the first TRUE condition.' },
            { name: 'IFNA', syntax: 'IFNA(Value, AlternateValue)', description: 'Returns Value unless it is the #N/A error, in which case returns AlternateValue.' },
            { name: 'IFERROR', syntax: 'IFERROR(Value, AlternateValue)', description: 'Returns Value unless it is an error, in which case returns AlternateValue.' },
            { name: 'NOT', syntax: 'NOT(LogicalValue)', description: 'Inverts a logical value.' },
            { name: 'OR', syntax: 'OR(LogicalValue1, LogicalValue2, ...LogicalValueN)', description: 'Returns TRUE if at least one argument is TRUE.' },
            { name: 'SWITCH', syntax: 'SWITCH(Expression, Value1, Result1 [, Value2, Result2 [, ..., DefaultResult]])', description: 'Returns the result corresponding to the first matching value.' },
            { name: 'TRUE', syntax: 'TRUE()', description: 'Returns the logical value TRUE.' },
            { name: 'XOR', syntax: 'XOR(LogicalValue1, LogicalValue2, ...LogicalValueN)', description: 'Returns TRUE if an odd number of arguments evaluate to TRUE.' },
        ],
    },
    {
        title: 'Text',
        entries: [
            { name: 'CHAR', syntax: 'CHAR(Number)', description: 'Converts a number into a character according to the code table.' },
            { name: 'CLEAN', syntax: 'CLEAN("Text")', description: 'Returns text cleaned of line breaks and non-printable characters.' },
            { name: 'CODE', syntax: 'CODE("Text")', description: 'Returns a numeric code for the first character in a string.' },
            { name: 'CONCATENATE', syntax: 'CONCATENATE("Text1", "Text2", ..."TextN")', description: 'Combines several text strings into one string.' },
            { name: 'EXACT', syntax: 'EXACT(Text1, Text2)', description: 'Returns TRUE if both text strings are exactly the same.' },
            { name: 'FIND', syntax: 'FIND("FindText", "WithinText"[, StartNumber])', description: 'Returns the location of one text string inside another (case-sensitive).' },
            { name: 'LEFT', syntax: 'LEFT("Text", Number)', description: 'Extracts a given number of characters from the left side of a string.' },
            { name: 'LEN', syntax: 'LEN("Text")', description: 'Returns the length of a given text.' },
            { name: 'LOWER', syntax: 'LOWER(Text)', description: 'Returns text converted to lowercase.' },
            { name: 'MID', syntax: 'MID(Text, StartPosition, Length)', description: 'Returns a substring of a given length from a start position.' },
            { name: 'N', syntax: 'N(Value)', description: 'Converts a value to a number.' },
            { name: 'PROPER', syntax: 'PROPER("Text")', description: 'Capitalizes the first letter of each word in a string.' },
            { name: 'REPLACE', syntax: 'REPLACE(Text, StartPosition, Length, NewText)', description: 'Replaces a substring of a given length starting at a position.' },
            { name: 'REPT', syntax: 'REPT("Text", Number)', description: 'Repeats text a given number of times.' },
            { name: 'RIGHT', syntax: 'RIGHT("Text", Number)', description: 'Extracts a given number of characters from the right side of a string.' },
            { name: 'SEARCH', syntax: 'SEARCH(SearchString, Text[, StartPosition])', description: 'Returns the location of a search string inside text (case-insensitive).' },
            { name: 'SPLIT', syntax: 'SPLIT(Text, Index)', description: 'Divides text using a space as the separator and returns the substring at an index.' },
            { name: 'SUBSTITUTE', syntax: 'SUBSTITUTE(Text, OldText, NewText, [Occurrence])', description: 'Returns text where old text has been replaced by new text.' },
            { name: 'T', syntax: 'T(Value)', description: 'Returns the text if the value is text; otherwise returns an empty string.' },
            { name: 'TEXT', syntax: 'TEXT(Number, Format)', description: 'Converts a number into text according to a given format.' },
            { name: 'TRIM', syntax: 'TRIM("Text")', description: 'Strips extra spaces from text.' },
            { name: 'UNICHAR', syntax: 'UNICHAR(Number)', description: 'Returns the character created from a given code point.' },
            { name: 'UNICODE', syntax: 'UNICODE(Text)', description: 'Returns the Unicode code point of the first character of a string.' },
            { name: 'UPPER', syntax: 'UPPER(Text)', description: 'Returns text converted to uppercase.' },
            { name: 'VALUE', syntax: 'VALUE(Text)', description: 'Parses a number, date, time, or currency from a text string.' },
        ],
    },
    {
        title: 'Date and time',
        entries: [
            { name: 'DATE', syntax: 'DATE(Year, Month, Day)', description: 'Returns the specified date as a serial number (days since the null date).' },
            { name: 'DATEDIF', syntax: 'DATEDIF(Date1, Date2, Unit)', description: 'Calculates the distance between two dates in a given unit.' },
            { name: 'DATEVALUE', syntax: 'DATEVALUE(DateString)', description: 'Parses a date string and returns days since the null date.' },
            { name: 'DAY', syntax: 'DAY(Number)', description: 'Returns the day of the given date value.' },
            { name: 'DAYS', syntax: 'DAYS(Date2, Date1)', description: 'Calculates the difference between two date values, in days.' },
            { name: 'DAYS360', syntax: 'DAYS360(Date2, Date1[, Format])', description: 'Calculates the difference between dates using a 360-day year.' },
            { name: 'EDATE', syntax: 'EDATE(StartDate, Months)', description: 'Shifts a start date by a number of months and returns the serial date.' },
            { name: 'EOMONTH', syntax: 'EOMONTH(StartDate, Months)', description: 'Returns the last day of the month a given number of months from the start date.' },
            { name: 'HOUR', syntax: 'HOUR(Time)', description: 'Returns the hour component of a given time.' },
            { name: 'INTERVAL', syntax: 'INTERVAL(Seconds)', description: 'Returns an ISO 8601 interval string from a number of seconds.' },
            { name: 'ISOWEEKNUM', syntax: 'ISOWEEKNUM(Date)', description: 'Returns the ISO 8601 week number for the date.' },
            { name: 'MINUTE', syntax: 'MINUTE(Time)', description: 'Returns the minute component of a given time.' },
            { name: 'MONTH', syntax: 'MONTH(Number)', description: 'Returns the month for the given date value.' },
            { name: 'NETWORKDAYS', syntax: 'NETWORKDAYS(Date1, Date2[, Holidays])', description: 'Returns the number of working days between two dates.' },
            { name: 'NETWORKDAYS.INTL', syntax: 'NETWORKDAYS.INTL(Date1, Date2[, Mode [, Holidays]])', description: 'Returns the number of working days between two dates with a custom weekend.' },
            { name: 'NOW', syntax: 'NOW()', description: 'Returns the current date and time as a serial number.' },
            { name: 'SECOND', syntax: 'SECOND(Time)', description: 'Returns the second component of a given time.' },
            { name: 'TIME', syntax: 'TIME(Hour, Minute, Second)', description: 'Returns a number representing the given time as a fraction of a day.' },
            { name: 'TIMEVALUE', syntax: 'TIMEVALUE(TimeString)', description: 'Parses a time string and returns a number as a fraction of a day.' },
            { name: 'TODAY', syntax: 'TODAY()', description: 'Returns the integer representing the current date.' },
            { name: 'WEEKDAY', syntax: 'WEEKDAY(Date, Type)', description: 'Returns a number between 1 and 7 representing the day of the week.' },
            { name: 'WEEKNUM', syntax: 'WEEKNUM(Date, Type)', description: 'Returns the week number for a given date.' },
            { name: 'WORKDAY', syntax: 'WORKDAY(Date, Shift[, Holidays])', description: 'Returns the working day a given number of days from a start date.' },
            { name: 'WORKDAY.INTL', syntax: 'WORKDAY.INTL(Date, Shift[, Mode[, Holidays]])', description: 'Returns the working day a given number of days from a start date with a custom weekend.' },
            { name: 'YEAR', syntax: 'YEAR(Number)', description: 'Returns the year for the given date value.' },
            { name: 'YEARFRAC', syntax: 'YEARFRAC(Date2, Date1[, Format])', description: 'Computes the difference between dates as a fraction of years.' },
        ],
    },
    {
        title: 'Statistical',
        entries: [
            { name: 'AVEDEV', syntax: 'AVEDEV(Number1, Number2, ...NumberN)', description: 'Returns the average absolute deviation of the arguments from their mean.' },
            { name: 'AVERAGE', syntax: 'AVERAGE(Number1, Number2, ...NumberN)', description: 'Returns the arithmetic mean of the arguments.' },
            { name: 'AVERAGEA', syntax: 'AVERAGEA(Value1, Value2, ...ValueN)', description: 'Returns the arithmetic mean of the arguments (text and logical values count as 0/1).' },
            { name: 'AVERAGEIF', syntax: 'AVERAGEIF(Range, Criterion [, AverageRange])', description: 'Returns the arithmetic mean of cells satisfying a condition.' },
            { name: 'BESSELI', syntax: 'BESSELI(X, N)', description: 'Returns the value of the modified Bessel function In(x).' },
            { name: 'BESSELJ', syntax: 'BESSELJ(X, N)', description: 'Returns the value of the Bessel function Jn(x).' },
            { name: 'BESSELK', syntax: 'BESSELK(X, N)', description: 'Returns the value of the modified Bessel function Kn(x).' },
            { name: 'BESSELY', syntax: 'BESSELY(X, N)', description: 'Returns the value of the Bessel function Yn(x).' },
            { name: 'BETA.DIST', syntax: 'BETA.DIST(X, Alpha, Beta, Cumulative[, A[, B]])', description: 'Returns the value of the beta distribution density.' },
            { name: 'BETADIST', syntax: 'BETADIST(X, Alpha, Beta, Cumulative[, A[, B]])', description: 'Returns the value of the beta distribution density.' },
            { name: 'BETA.INV', syntax: 'BETA.INV(Probability, Alpha, Beta[, A[, B]])', description: 'Returns the inverse of the beta distribution.' },
            { name: 'BETAINV', syntax: 'BETAINV(Probability, Alpha, Beta[, A[, B]])', description: 'Returns the inverse of the beta distribution.' },
            { name: 'BINOM.DIST', syntax: 'BINOM.DIST(Number, Trials, Probability, Cumulative)', description: 'Returns the binomial distribution density.' },
            { name: 'BINOMDIST', syntax: 'BINOMDIST(Number, Trials, Probability, Cumulative)', description: 'Returns the binomial distribution density.' },
            { name: 'BINOM.INV', syntax: 'BINOM.INV(Trials, Probability, Alpha)', description: 'Returns the smallest value for which the cumulative binomial distribution is ≥ Alpha.' },
            { name: 'CHIDIST', syntax: 'CHIDIST(X, Degrees)', description: 'Returns the right-tailed probability of the chi-squared distribution.' },
            { name: 'CHIDISTRT', syntax: 'CHIDISTRT(X, Degrees)', description: 'Returns the right-tailed probability of the chi-squared distribution.' },
            { name: 'CHIINV', syntax: 'CHIINV(Probability, Degrees)', description: 'Returns the inverse of the right-tailed chi-squared distribution.' },
            { name: 'CHIINVRT', syntax: 'CHIINVRT(Probability, Degrees)', description: 'Returns the inverse of the right-tailed chi-squared distribution.' },
            { name: 'CHISQ.DIST', syntax: 'CHISQ.DIST(X, Degrees, Cumulative)', description: 'Returns the chi-squared distribution value.' },
            { name: 'CHISQ.DIST.RT', syntax: 'CHISQ.DIST.RT(X, Degrees)', description: 'Returns the right-tailed probability of the chi-squared distribution.' },
            { name: 'CHISQ.INV', syntax: 'CHISQ.INV(Probability, Degrees)', description: 'Returns the inverse of the left-tailed chi-squared distribution.' },
            { name: 'CHISQ.INV.RT', syntax: 'CHISQ.INV.RT(Probability, Degrees)', description: 'Returns the inverse of the right-tailed chi-squared distribution.' },
            { name: 'CHISQ.TEST', syntax: 'CHISQ.TEST(Array1, Array2)', description: 'Returns the chi-squared test value for a dataset.' },
            { name: 'CHITEST', syntax: 'CHITEST(Array1, Array2)', description: 'Returns the chi-squared test value for a dataset.' },
            { name: 'CONFIDENCE', syntax: 'CONFIDENCE(Alpha, Stdev, Size)', description: 'Returns the upper confidence bound for the normal distribution.' },
            { name: 'CONFIDENCE.NORM', syntax: 'CONFIDENCE.NORM(Alpha, Stdev, Size)', description: 'Returns the upper confidence bound for the normal distribution.' },
            { name: 'CONFIDENCE.T', syntax: 'CONFIDENCE.T(Alpha, Stdev, Size)', description: 'Returns the upper confidence bound for the Student-t distribution.' },
            { name: 'CORREL', syntax: 'CORREL(Data1, Data2)', description: 'Returns the correlation coefficient between two datasets.' },
            { name: 'COUNT', syntax: 'COUNT(Value1, Value2, ...ValueN)', description: 'Counts how many numbers are in the list of arguments.' },
            { name: 'COUNTA', syntax: 'COUNTA(Value1, Value2, ...ValueN)', description: 'Counts how many values (non-empty) are in the list of arguments.' },
            { name: 'COUNTBLANK', syntax: 'COUNTBLANK(Range)', description: 'Returns the number of empty cells in a range.' },
            { name: 'COUNTIF', syntax: 'COUNTIF(Range, Criteria)', description: 'Returns the count of cells in a range meeting a criterion.' },
            { name: 'COUNTIFS', syntax: 'COUNTIFS(Range1, Criterion1 [, Range2, Criterion2 [, ...]])', description: 'Returns the count of cells meeting multiple criteria.' },
            { name: 'COVAR', syntax: 'COVAR(Data1, Data2)', description: 'Returns the covariance between datasets (population-normalized).' },
            { name: 'COVARIANCE.P', syntax: 'COVARIANCE.P(Data1, Data2)', description: 'Returns the covariance between datasets (population-normalized).' },
            { name: 'COVARIANCEP', syntax: 'COVARIANCEP(Data1, Data2)', description: 'Returns the covariance between datasets (population-normalized).' },
            { name: 'COVARIANCE.S', syntax: 'COVARIANCE.S(Data1, Data2)', description: 'Returns the covariance between datasets (sample-normalized).' },
            { name: 'COVARIANCES', syntax: 'COVARIANCES(Data1, Data2)', description: 'Returns the covariance between datasets (sample-normalized).' },
            { name: 'CRITBINOM', syntax: 'CRITBINOM(Trials, Probability, Alpha)', description: 'Returns the inverse binomial distribution value.' },
            { name: 'DEVSQ', syntax: 'DEVSQ(Number1, Number2, ...NumberN)', description: 'Returns the sum of squared deviations from the mean.' },
            { name: 'EXPON.DIST', syntax: 'EXPON.DIST(X, Lambda, Cumulative)', description: 'Returns the density of the exponential distribution.' },
            { name: 'EXPONDIST', syntax: 'EXPONDIST(X, Lambda, Cumulative)', description: 'Returns the density of the exponential distribution.' },
            { name: 'FDIST', syntax: 'FDIST(X, Degree1, Degree2)', description: 'Returns the right-tailed probability of the F distribution.' },
            { name: 'FINV', syntax: 'FINV(Probability, Degree1, Degree2)', description: 'Returns the inverse of the right-tailed F distribution.' },
            { name: 'F.DIST', syntax: 'F.DIST(X, Degree1, Degree2, Cumulative)', description: 'Returns the F distribution density.' },
            { name: 'F.DIST.RT', syntax: 'F.DIST.RT(X, Degree1, Degree2)', description: 'Returns the right-tailed probability of the F distribution.' },
            { name: 'FDISTRT', syntax: 'FDISTRT(X, Degree1, Degree2)', description: 'Returns the right-tailed probability of the F distribution.' },
            { name: 'F.INV', syntax: 'F.INV(Probability, Degree1, Degree2)', description: 'Returns the inverse of the left-tailed F distribution.' },
            { name: 'F.INV.RT', syntax: 'F.INV.RT(Probability, Degree1, Degree2)', description: 'Returns the inverse of the right-tailed F distribution.' },
            { name: 'FINVRT', syntax: 'FINVRT(Probability, Degree1, Degree2)', description: 'Returns the inverse of the right-tailed F distribution.' },
            { name: 'FISHER', syntax: 'FISHER(Number)', description: 'Returns the Fisher transformation value.' },
            { name: 'FISHERINV', syntax: 'FISHERINV(Number)', description: 'Returns the inverse of the Fisher transformation.' },
            { name: 'F.TEST', syntax: 'F.TEST(Array1, Array2)', description: 'Returns the F-test value for a dataset.' },
            { name: 'FTEST', syntax: 'FTEST(Array1, Array2)', description: 'Returns the F-test value for a dataset.' },
            { name: 'GAMMA', syntax: 'GAMMA(Number)', description: 'Returns the value of the gamma function.' },
            { name: 'GAMMA.DIST', syntax: 'GAMMA.DIST(X, Alpha, Beta, Cumulative)', description: 'Returns the gamma distribution density.' },
            { name: 'GAMMADIST', syntax: 'GAMMADIST(X, Alpha, Beta, Cumulative)', description: 'Returns the gamma distribution density.' },
            { name: 'GAMMALN', syntax: 'GAMMALN(Number)', description: 'Returns the natural logarithm of the gamma function.' },
            { name: 'GAMMALN.PRECISE', syntax: 'GAMMALN.PRECISE(Number)', description: 'Returns the natural logarithm of the gamma function.' },
            { name: 'GAMMA.INV', syntax: 'GAMMA.INV(Probability, Alpha, Beta)', description: 'Returns the inverse of the gamma distribution.' },
            { name: 'GAMMAINV', syntax: 'GAMMAINV(Probability, Alpha, Beta)', description: 'Returns the inverse of the gamma distribution.' },
            { name: 'GAUSS', syntax: 'GAUSS(Number)', description: 'Returns the probability that a Gaussian variable is between the mean and Number standard deviations.' },
            { name: 'GEOMEAN', syntax: 'GEOMEAN(Number1, Number2, ...NumberN)', description: 'Returns the geometric mean of the arguments.' },
            { name: 'HARMEAN', syntax: 'HARMEAN(Number1, Number2, ...NumberN)', description: 'Returns the harmonic mean of the arguments.' },
            { name: 'HYPGEOMDIST', syntax: 'HYPGEOMDIST(SampleS, NumberSample, PopulationS, NumberPop, Cumulative)', description: 'Returns the hypergeometric distribution density.' },
            { name: 'HYPGEOM.DIST', syntax: 'HYPGEOM.DIST(SampleS, NumberSample, PopulationS, NumberPop, Cumulative)', description: 'Returns the hypergeometric distribution density.' },
            { name: 'LARGE', syntax: 'LARGE(Range, K)', description: 'Returns the K-th largest value in a range.' },
            { name: 'LOGNORM.DIST', syntax: 'LOGNORM.DIST(X, Mean, Stddev, Cumulative)', description: 'Returns the lognormal distribution density.' },
            { name: 'LOGNORMDIST', syntax: 'LOGNORMDIST(X, Mean, Stddev, Cumulative)', description: 'Returns the lognormal distribution density.' },
            { name: 'LOGNORM.INV', syntax: 'LOGNORM.INV(Probability, Mean, Stddev)', description: 'Returns the inverse of the lognormal distribution.' },
            { name: 'LOGNORMINV', syntax: 'LOGNORMINV(Probability, Mean, Stddev)', description: 'Returns the inverse of the lognormal distribution.' },
            { name: 'LOGINV', syntax: 'LOGINV(Probability, Mean, Stddev)', description: 'Returns the inverse of the lognormal distribution.' },
            { name: 'MAX', syntax: 'MAX(Number1, Number2, ...NumberN)', description: 'Returns the maximum value in a list of arguments.' },
            { name: 'MAXA', syntax: 'MAXA(Value1, Value2, ...ValueN)', description: 'Returns the maximum value in a list of arguments (text and logical values count).' },
            { name: 'MAXIFS', syntax: 'MAXIFS(MaxRange, CriterionRange1, Criterion1 [, ...])', description: 'Returns the maximum value of cells meeting multiple criteria.' },
            { name: 'MEDIAN', syntax: 'MEDIAN(Number1, Number2, ...NumberN)', description: 'Returns the median of a set of numbers.' },
            { name: 'MIN', syntax: 'MIN(Number1, Number2, ...NumberN)', description: 'Returns the minimum value in a list of arguments.' },
            { name: 'MINA', syntax: 'MINA(Value1, Value2, ...ValueN)', description: 'Returns the minimum value in a list of arguments (text and logical values count).' },
            { name: 'MINIFS', syntax: 'MINIFS(MinRange, CriterionRange1, Criterion1 [, ...])', description: 'Returns the minimum value of cells meeting multiple criteria.' },
            { name: 'NEGBINOM.DIST', syntax: 'NEGBINOM.DIST(Failures, Successes, Probability, Cumulative)', description: 'Returns the negative binomial distribution density.' },
            { name: 'NEGBINOMDIST', syntax: 'NEGBINOMDIST(Failures, Successes, Probability, Cumulative)', description: 'Returns the negative binomial distribution density.' },
            { name: 'NORM.DIST', syntax: 'NORM.DIST(X, Mean, Stddev, Cumulative)', description: 'Returns the normal distribution density.' },
            { name: 'NORMDIST', syntax: 'NORMDIST(X, Mean, Stddev, Cumulative)', description: 'Returns the normal distribution density.' },
            { name: 'NORM.S.DIST', syntax: 'NORM.S.DIST(X, Cumulative)', description: 'Returns the standard normal distribution density.' },
            { name: 'NORMSDIST', syntax: 'NORMSDIST(X, Cumulative)', description: 'Returns the standard normal distribution density.' },
            { name: 'NORM.INV', syntax: 'NORM.INV(Probability, Mean, Stddev)', description: 'Returns the inverse of the normal distribution.' },
            { name: 'NORMINV', syntax: 'NORMINV(Probability, Mean, Stddev)', description: 'Returns the inverse of the normal distribution.' },
            { name: 'NORM.S.INV', syntax: 'NORM.S.INV(Probability)', description: 'Returns the inverse of the standard normal distribution.' },
            { name: 'NORMSINV', syntax: 'NORMSINV(Probability)', description: 'Returns the inverse of the standard normal distribution.' },
            { name: 'PEARSON', syntax: 'PEARSON(Data1, Data2)', description: 'Returns the Pearson correlation coefficient between two datasets.' },
            { name: 'PHI', syntax: 'PHI(X)', description: 'Returns the probability density of the standard normal distribution.' },
            { name: 'POISSON', syntax: 'POISSON(X, Mean, Cumulative)', description: 'Returns the Poisson distribution density.' },
            { name: 'POISSON.DIST', syntax: 'POISSON.DIST(X, Mean, Cumulative)', description: 'Returns the Poisson distribution density.' },
            { name: 'POISSONDIST', syntax: 'POISSONDIST(X, Mean, Cumulative)', description: 'Returns the Poisson distribution density.' },
            { name: 'RSQ', syntax: 'RSQ(Data1, Data2)', description: 'Returns the squared Pearson correlation coefficient.' },
            { name: 'SKEW', syntax: 'SKEW(Number1, Number2, ...NumberN)', description: 'Returns the skewness of a sample.' },
            { name: 'SKEW.P', syntax: 'SKEW.P(Number1, Number2, ...NumberN)', description: 'Returns the skewness of a population.' },
            { name: 'SKEWP', syntax: 'SKEWP(Number1, Number2, ...NumberN)', description: 'Returns the skewness of a population.' },
            { name: 'SLOPE', syntax: 'SLOPE(KnownY, KnownX)', description: 'Returns the slope of a linear regression line.' },
            { name: 'SMALL', syntax: 'SMALL(Range, K)', description: 'Returns the K-th smallest value in a range.' },
            { name: 'STANDARDIZE', syntax: 'STANDARDIZE(X, Mean, Stddev)', description: 'Returns a normalized value with respect to mean and standard deviation.' },
            { name: 'STDEV', syntax: 'STDEV(Value1, Value2, ...ValueN)', description: 'Returns the standard deviation of a sample.' },
            { name: 'STDEVA', syntax: 'STDEVA(Value1, Value2, ...ValueN)', description: 'Returns the standard deviation of a sample (text and logical values count).' },
            { name: 'STDEVP', syntax: 'STDEVP(Value1, Value2, ...ValueN)', description: 'Returns the standard deviation of a population.' },
            { name: 'STDEV.P', syntax: 'STDEV.P(Value1, Value2, ...ValueN)', description: 'Returns the standard deviation of a population.' },
            { name: 'STDEVPA', syntax: 'STDEVPA(Value1, Value2, ...ValueN)', description: 'Returns the standard deviation of a population (text and logical values count).' },
            { name: 'STDEV.S', syntax: 'STDEV.S(Value1, Value2, ...ValueN)', description: 'Returns the standard deviation of a sample.' },
            { name: 'STDEVS', syntax: 'STDEVS(Value1, Value2, ...ValueN)', description: 'Returns the standard deviation of a sample.' },
            { name: 'STEYX', syntax: 'STEYX(KnownY, KnownX)', description: 'Returns the standard error of the predicted y-value.' },
            { name: 'TDIST', syntax: 'TDIST(X, Degrees, Mode)', description: 'Returns the Student-t distribution density.' },
            { name: 'T.DIST', syntax: 'T.DIST(X, Degrees, Cumulative)', description: 'Returns the Student-t distribution density.' },
            { name: 'T.DIST.2T', syntax: 'T.DIST.2T(X, Degrees)', description: 'Returns the two-tailed Student-t distribution probability.' },
            { name: 'TDIST2T', syntax: 'TDIST2T(X, Degrees)', description: 'Returns the two-tailed Student-t distribution probability.' },
            { name: 'T.DIST.RT', syntax: 'T.DIST.RT(X, Degrees)', description: 'Returns the right-tailed Student-t distribution probability.' },
            { name: 'TDISTRT', syntax: 'TDISTRT(X, Degrees)', description: 'Returns the right-tailed Student-t distribution probability.' },
            { name: 'TINV', syntax: 'TINV(Probability, Degrees)', description: 'Returns the inverse two-tailed Student-t distribution.' },
            { name: 'T.INV', syntax: 'T.INV(Probability, Degrees)', description: 'Returns the inverse of the Student-t distribution.' },
            { name: 'T.INV.2T', syntax: 'T.INV.2T(Probability, Degrees)', description: 'Returns the inverse two-tailed Student-t distribution.' },
            { name: 'TINV2T', syntax: 'TINV2T(Probability, Degrees)', description: 'Returns the inverse two-tailed Student-t distribution.' },
            { name: 'TTEST', syntax: 'TTEST(Array1, Array2)', description: 'Returns the t-test value for a dataset.' },
            { name: 'T.TEST', syntax: 'T.TEST(Array1, Array2)', description: 'Returns the t-test value for a dataset.' },
            { name: 'VAR', syntax: 'VAR(Value1, Value2, ...ValueN)', description: 'Returns the variance of a sample.' },
            { name: 'VARA', syntax: 'VARA(Value1, Value2, ...ValueN)', description: 'Returns the variance of a sample (text and logical values count).' },
            { name: 'VARP', syntax: 'VARP(Value1, Value2, ...ValueN)', description: 'Returns the variance of a population.' },
            { name: 'VAR.P', syntax: 'VAR.P(Value1, Value2, ...ValueN)', description: 'Returns the variance of a population.' },
            { name: 'VARPA', syntax: 'VARPA(Value1, Value2, ...ValueN)', description: 'Returns the variance of a population (text and logical values count).' },
            { name: 'VAR.S', syntax: 'VAR.S(Value1, Value2, ...ValueN)', description: 'Returns the variance of a sample.' },
            { name: 'VARS', syntax: 'VARS(Value1, Value2, ...ValueN)', description: 'Returns the variance of a sample.' },
            { name: 'WEIBULL', syntax: 'WEIBULL(X, Alpha, Beta, Cumulative)', description: 'Returns the Weibull distribution density.' },
            { name: 'WEIBULL.DIST', syntax: 'WEIBULL.DIST(X, Alpha, Beta, Cumulative)', description: 'Returns the Weibull distribution density.' },
            { name: 'WEIBULLDIST', syntax: 'WEIBULLDIST(X, Alpha, Beta, Cumulative)', description: 'Returns the Weibull distribution density.' },
            { name: 'Z.TEST', syntax: 'Z.TEST(Array, X[, Sigma])', description: 'Returns the z-test value for a dataset.' },
            { name: 'ZTEST', syntax: 'ZTEST(Array, X[, Sigma])', description: 'Returns the z-test value for a dataset.' },
        ],
    },
    {
        title: 'Financial',
        entries: [
            { name: 'CUMIPMT', syntax: 'CUMIPMT(Rate, Nper, Pv, Start, End, Type)', description: 'Returns the cumulative interest paid on a loan between two periods.' },
            { name: 'CUMPRINC', syntax: 'CUMPRINC(Rate, Nper, Pv, Start, End, Type)', description: 'Returns the cumulative principal paid on a loan between two periods.' },
            { name: 'DB', syntax: 'DB(Cost, Salvage, Life, Period[, Month])', description: 'Returns depreciation using the fixed-declining balance method.' },
            { name: 'DDB', syntax: 'DDB(Cost, Salvage, Life, Period[, Factor])', description: 'Returns depreciation using the double-declining balance method.' },
            { name: 'DOLLARDE', syntax: 'DOLLARDE(Price, Fraction)', description: 'Converts a price in fractional notation to a decimal number.' },
            { name: 'DOLLARFR', syntax: 'DOLLARFR(Price, Fraction)', description: 'Converts a decimal price to fractional notation.' },
            { name: 'EFFECT', syntax: 'EFFECT(NominalRate, NPerY)', description: 'Calculates the effective annual interest rate from the nominal rate.' },
            { name: 'FV', syntax: 'FV(Rate, Nper, Pmt[, Pv,[ Type]])', description: 'Returns the future value of an investment.' },
            { name: 'FVSCHEDULE', syntax: 'FVSCHEDULE(Pv, Schedule)', description: 'Returns the future value of an investment based on a rate schedule.' },
            { name: 'IPMT', syntax: 'IPMT(Rate, Per, Nper, Pv[, Fv[, Type]])', description: 'Returns the interest portion of a loan payment in a given period.' },
            { name: 'IRR', syntax: 'IRR(Values[, Guess])', description: 'Returns the internal rate of return for a series of cash flows.' },
            { name: 'ISPMT', syntax: 'ISPMT(Rate, Per, Nper, Value)', description: 'Returns the interest paid for a given period of an investment.' },
            { name: 'MIRR', syntax: 'MIRR(Flows, FRate, RRate)', description: 'Returns the modified internal rate of return for cash flows.' },
            { name: 'NOMINAL', syntax: 'NOMINAL(EffectRate, NPerY)', description: 'Returns the nominal interest rate.' },
            { name: 'NPER', syntax: 'NPER(Rate, Pmt, Pv[, Fv[, Type]])', description: 'Returns the number of periods for an investment.' },
            { name: 'NPV', syntax: 'NPV(Rate, Value1, Value2, ...ValueN)', description: 'Returns the net present value of an investment.' },
            { name: 'PDURATION', syntax: 'PDURATION(Rate, Pv, Fv)', description: 'Returns the number of periods required for an investment to reach a specific value.' },
            { name: 'PMT', syntax: 'PMT(Rate, Nper, Pv[, Fv[, Type]])', description: 'Returns the periodic payment for a loan.' },
            { name: 'PPMT', syntax: 'PPMT(Rate, Per, Nper, Pv[, Fv[, Type]])', description: 'Returns the principal portion of a loan payment.' },
            { name: 'PV', syntax: 'PV(Rate, Nper, Pmt[, Fv[, Type]])', description: 'Returns the present value of an investment.' },
            { name: 'RATE', syntax: 'RATE(Nper, Pmt, Pv[, Fv[, Type[, Guess]]])', description: 'Returns the interest rate per period of an annuity.' },
            { name: 'RRI', syntax: 'RRI(Nper, Pv, Fv)', description: 'Returns the equivalent interest rate for an investment growing from Pv to Fv.' },
            { name: 'SLN', syntax: 'SLN(Cost, Salvage, Life)', description: 'Returns the depreciation using the straight-line method.' },
            { name: 'SYD', syntax: 'SYD(Cost, Salvage, Life, Period)', description: 'Returns the sum-of-years depreciation for an asset over a period.' },
            { name: 'TBILLEQ', syntax: 'TBILLEQ(Settlement, Maturity, Discount)', description: 'Returns the bond-equivalent yield for a Treasury bill.' },
            { name: 'TBILLPRICE', syntax: 'TBILLPRICE(Settlement, Maturity, Discount)', description: 'Returns the price per $100 face value for a Treasury bill.' },
            { name: 'TBILLYIELD', syntax: 'TBILLYIELD(Settlement, Maturity, Price)', description: 'Returns the yield for a Treasury bill.' },
            { name: 'XNPV', syntax: 'XNPV(Rate, Payments, Dates)', description: 'Returns the net present value for a schedule of irregular cash flows.' },
        ],
    },
    {
        title: 'Lookup and reference',
        entries: [
            { name: 'ADDRESS', syntax: 'ADDRESS(Row, Column[, AbsoluteRelativeMode[, UseA1Notation[, Sheet]]])', description: 'Returns a cell reference as a string.' },
            { name: 'CHOOSE', syntax: 'CHOOSE(Index, Value1, Value2, ...ValueN)', description: 'Uses an index to return a value from a list of values.' },
            { name: 'COLUMN', syntax: 'COLUMN([Reference])', description: 'Returns the column number of a given reference or of the formula cell.' },
            { name: 'COLUMNS', syntax: 'COLUMNS(Array)', description: 'Returns the number of columns in the given reference.' },
            { name: 'FORMULATEXT', syntax: 'FORMULATEXT(Reference)', description: 'Returns the formula in a given cell as a string.' },
            { name: 'HLOOKUP', syntax: 'HLOOKUP(SearchCriterion, Array, Index, SortOrder)', description: 'Searches the first row of an array for a value and returns a value from the same column.' },
            { name: 'HYPERLINK', syntax: 'HYPERLINK(Url[, LinkLabel])', description: 'Stores a URL in the cell\'s metadata.' },
            { name: 'INDEX', syntax: 'INDEX(Range, Row [, Column])', description: 'Returns the contents of a cell by row and column number within a range.' },
            { name: 'MATCH', syntax: 'MATCH(SearchCriterion, LookupArray [, MatchType])', description: 'Returns the relative position of a matching item in an array.' },
            { name: 'OFFSET', syntax: 'OFFSET(Reference, Rows, Columns, Height, Width)', description: 'Returns the value of a cell offset by a number of rows and columns.' },
            { name: 'ROW', syntax: 'ROW([Reference])', description: 'Returns the row number of a given reference or of the formula cell.' },
            { name: 'ROWS', syntax: 'ROWS(Array)', description: 'Returns the number of rows in the given reference.' },
            { name: 'VLOOKUP', syntax: 'VLOOKUP(SearchCriterion, Array, Index, SortOrder)', description: 'Searches the first column of an array for a value and returns a value from the same row.' },
            { name: 'XLOOKUP', syntax: 'XLOOKUP(LookupValue, LookupArray, ReturnArray, [IfNotFound], [MatchMode], [SearchMode])', description: 'Searches for a key in a range and returns the closest match.' },
        ],
    },
    {
        title: 'Information',
        entries: [
            { name: 'ISBINARY', syntax: 'ISBINARY(Value)', description: 'Returns TRUE if the provided value is a valid binary string.' },
            { name: 'ISBLANK', syntax: 'ISBLANK(Value)', description: 'Returns TRUE if the reference to a cell is blank.' },
            { name: 'ISERR', syntax: 'ISERR(Value)', description: 'Returns TRUE if the value is an error other than #N/A.' },
            { name: 'ISERROR', syntax: 'ISERROR(Value)', description: 'Returns TRUE if the value is any error value.' },
            { name: 'ISEVEN', syntax: 'ISEVEN(Value)', description: 'Returns TRUE if the value is an even integer.' },
            { name: 'ISFORMULA', syntax: 'ISFORMULA(Value)', description: 'Returns TRUE if the referenced cell contains a formula.' },
            { name: 'ISLOGICAL', syntax: 'ISLOGICAL(Value)', description: 'Returns TRUE for a logical value (TRUE or FALSE).' },
            { name: 'ISNA', syntax: 'ISNA(Value)', description: 'Returns TRUE if the value is the #N/A error.' },
            { name: 'ISNONTEXT', syntax: 'ISNONTEXT(Value)', description: 'Returns TRUE if the value is not text.' },
            { name: 'ISNUMBER', syntax: 'ISNUMBER(Value)', description: 'Returns TRUE if the value is a number.' },
            { name: 'ISODD', syntax: 'ISODD(Value)', description: 'Returns TRUE if the value is an odd integer.' },
            { name: 'ISREF', syntax: 'ISREF(Value)', description: 'Returns TRUE if the value is the #REF! error.' },
            { name: 'ISTEXT', syntax: 'ISTEXT(Value)', description: 'Returns TRUE if the cell contents are text.' },
            { name: 'SHEET', syntax: 'SHEET([Value])', description: 'Returns the sheet number of a given value or of the formula\'s sheet.' },
            { name: 'SHEETS', syntax: 'SHEETS([Value])', description: 'Returns the number of sheets in a reference or in the workbook.' },
            { name: 'NA', syntax: 'NA()', description: 'Returns the #N/A error value.' },
            { name: 'VERSION', syntax: 'VERSION()', description: 'Returns the HyperFormula version string powering the formula engine.' },
        ],
    },
    {
        title: 'Engineering',
        entries: [
            { name: 'BIN2DEC', syntax: 'BIN2DEC(Number)', description: 'Converts a binary number to decimal.' },
            { name: 'BIN2HEX', syntax: 'BIN2HEX(Number, Places)', description: 'Converts a binary number to hexadecimal.' },
            { name: 'BIN2OCT', syntax: 'BIN2OCT(Number, Places)', description: 'Converts a binary number to octal.' },
            { name: 'BITAND', syntax: 'BITAND(Number1, Number2)', description: 'Returns a bitwise logical AND of two numbers.' },
            { name: 'BITLSHIFT', syntax: 'BITLSHIFT(Number, Shift)', description: 'Shifts a number left by N bits.' },
            { name: 'BITOR', syntax: 'BITOR(Number1, Number2)', description: 'Returns a bitwise logical OR of two numbers.' },
            { name: 'BITRSHIFT', syntax: 'BITRSHIFT(Number, Shift)', description: 'Shifts a number right by N bits.' },
            { name: 'BITXOR', syntax: 'BITXOR(Number1, Number2)', description: 'Returns the bitwise XOR of two numbers.' },
            { name: 'COMPLEX', syntax: 'COMPLEX(Re, Im[, Symbol])', description: 'Returns a complex number from real and imaginary parts.' },
            { name: 'DEC2BIN', syntax: 'DEC2BIN(Number, Places)', description: 'Converts a decimal number to binary.' },
            { name: 'DEC2HEX', syntax: 'DEC2HEX(Number, Places)', description: 'Converts a decimal number to hexadecimal.' },
            { name: 'DEC2OCT', syntax: 'DEC2OCT(Number, Places)', description: 'Converts a decimal number to octal.' },
            { name: 'DELTA', syntax: 'DELTA(Number1, Number2)', description: 'Returns 1 if two numbers are equal, 0 otherwise.' },
            { name: 'ERF', syntax: 'ERF(LowerLimit[, UpperLimit])', description: 'Returns the value of the Gauss error integral.' },
            { name: 'ERFC', syntax: 'ERFC(LowerLimit)', description: 'Returns the complementary Gauss error integral.' },
            { name: 'HEX2BIN', syntax: 'HEX2BIN(Number, Places)', description: 'Converts a hexadecimal number to binary.' },
            { name: 'HEX2DEC', syntax: 'HEX2DEC(Number)', description: 'Converts a hexadecimal number to decimal.' },
            { name: 'HEX2OCT', syntax: 'HEX2OCT(Number, Places)', description: 'Converts a hexadecimal number to octal.' },
            { name: 'IMABS', syntax: 'IMABS(Complex)', description: 'Returns the modulus (absolute value) of a complex number.' },
            { name: 'IMAGINARY', syntax: 'IMAGINARY(Complex)', description: 'Returns the imaginary part of a complex number.' },
            { name: 'IMARGUMENT', syntax: 'IMARGUMENT(Complex)', description: 'Returns the argument θ of a complex number.' },
            { name: 'IMCONJUGATE', syntax: 'IMCONJUGATE(Complex)', description: 'Returns the conjugate of a complex number.' },
            { name: 'IMCOS', syntax: 'IMCOS(Complex)', description: 'Returns the cosine of a complex number.' },
            { name: 'IMCOSH', syntax: 'IMCOSH(Complex)', description: 'Returns the hyperbolic cosine of a complex number.' },
            { name: 'IMCOT', syntax: 'IMCOT(Complex)', description: 'Returns the cotangent of a complex number.' },
            { name: 'IMCSC', syntax: 'IMCSC(Complex)', description: 'Returns the cosecant of a complex number.' },
            { name: 'IMCSCH', syntax: 'IMCSCH(Complex)', description: 'Returns the hyperbolic cosecant of a complex number.' },
            { name: 'IMDIV', syntax: 'IMDIV(Complex1, Complex2)', description: 'Divides two complex numbers.' },
            { name: 'IMEXP', syntax: 'IMEXP(Complex)', description: 'Returns the exponent of a complex number.' },
            { name: 'IMLN', syntax: 'IMLN(Complex)', description: 'Returns the natural logarithm of a complex number.' },
            { name: 'IMLOG2', syntax: 'IMLOG2(Complex)', description: 'Returns the base-2 logarithm of a complex number.' },
            { name: 'IMLOG10', syntax: 'IMLOG10(Complex)', description: 'Returns the base-10 logarithm of a complex number.' },
            { name: 'IMPOWER', syntax: 'IMPOWER(Complex, Number)', description: 'Returns a complex number raised to a given power.' },
            { name: 'IMPRODUCT', syntax: 'IMPRODUCT(Complex1, Complex2, ...ComplexN)', description: 'Multiplies complex numbers.' },
            { name: 'IMREAL', syntax: 'IMREAL(Complex)', description: 'Returns the real part of a complex number.' },
            { name: 'IMSEC', syntax: 'IMSEC(Complex)', description: 'Returns the secant of a complex number.' },
            { name: 'IMSECH', syntax: 'IMSECH(Complex)', description: 'Returns the hyperbolic secant of a complex number.' },
            { name: 'IMSIN', syntax: 'IMSIN(Complex)', description: 'Returns the sine of a complex number.' },
            { name: 'IMSINH', syntax: 'IMSINH(Complex)', description: 'Returns the hyperbolic sine of a complex number.' },
            { name: 'IMSQRT', syntax: 'IMSQRT(Complex)', description: 'Returns the square root of a complex number.' },
            { name: 'IMSUB', syntax: 'IMSUB(Complex1, Complex2)', description: 'Subtracts two complex numbers.' },
            { name: 'IMSUM', syntax: 'IMSUM(Complex1, Complex2, ...ComplexN)', description: 'Adds complex numbers.' },
            { name: 'IMTAN', syntax: 'IMTAN(Complex)', description: 'Returns the tangent of a complex number.' },
            { name: 'OCT2BIN', syntax: 'OCT2BIN(Number, Places)', description: 'Converts an octal number to binary.' },
            { name: 'OCT2DEC', syntax: 'OCT2DEC(Number)', description: 'Converts an octal number to decimal.' },
            { name: 'OCT2HEX', syntax: 'OCT2HEX(Number, Places)', description: 'Converts an octal number to hexadecimal.' },
        ],
    },
    {
        title: 'Operator',
        entries: [
            { name: 'HF.ADD', syntax: 'HF.ADD(Number, Number)', description: 'Adds two values. Implements the `+` operator.' },
            { name: 'HF.CONCAT', syntax: 'HF.CONCAT(String, String)', description: 'Concatenates two strings. Implements the `&` operator.' },
            { name: 'HF.DIVIDE', syntax: 'HF.DIVIDE(Number, Number)', description: 'Divides two values. Implements the `/` operator.' },
            { name: 'HF.EQ', syntax: 'HF.EQ(Value, Value)', description: 'Tests two values for equality. Implements the `=` operator.' },
            { name: 'HF.LTE', syntax: 'HF.LTE(Value, Value)', description: 'Tests two values for the less-than-or-equal relation. Implements the `<=` operator.' },
            { name: 'HF.LT', syntax: 'HF.LT(Value, Value)', description: 'Tests two values for the less-than relation. Implements the `<` operator.' },
            { name: 'HF.GTE', syntax: 'HF.GTE(Value, Value)', description: 'Tests two values for the greater-than-or-equal relation. Implements the `>=` operator.' },
            { name: 'HF.GT', syntax: 'HF.GT(Value, Value)', description: 'Tests two values for the greater-than relation. Implements the `>` operator.' },
            { name: 'HF.MINUS', syntax: 'HF.MINUS(Number, Number)', description: 'Subtracts two values. Implements the binary `-` operator.' },
            { name: 'HF.MULTIPLY', syntax: 'HF.MULTIPLY(Number, Number)', description: 'Multiplies two values. Implements the `*` operator.' },
            { name: 'HF.NE', syntax: 'HF.NE(Value, Value)', description: 'Tests two values for inequality. Implements the `<>` operator.' },
            { name: 'HF.POW', syntax: 'HF.POW(Number, Number)', description: 'Raises a value to a power. Implements the `^` operator.' },
            { name: 'HF.UMINUS', syntax: 'HF.UMINUS(Number)', description: 'Negates a value. Implements the unary `-` operator.' },
            { name: 'HF.UNARY_PERCENT', syntax: 'HF.UNARY_PERCENT(Number)', description: 'Applies the percent operator (divides by 100).' },
            { name: 'HF.UPLUS', syntax: 'HF.UPLUS(Number)', description: 'Applies the unary `+` operator.' },
        ],
    },
    {
        title: 'Matrix',
        entries: [
            { name: 'MMULT', syntax: 'MMULT(Array1, Array2)', description: 'Returns the matrix product of two arrays.' },
            { name: 'MEDIANPOOL', syntax: 'MEDIANPOOL(Range, WindowSize, Stride)', description: 'Returns a smaller range that is the median of a sliding window.' },
            { name: 'MAXPOOL', syntax: 'MAXPOOL(Range, WindowSize, Stride)', description: 'Returns a smaller range that is the maximum of a sliding window.' },
            { name: 'TRANSPOSE', syntax: 'TRANSPOSE(Array)', description: 'Transposes the rows and columns of an array.' },
        ],
    },
    {
        title: 'Array manipulation',
        entries: [
            { name: 'ARRAYFORMULA', syntax: 'ARRAYFORMULA(Formula)', description: 'Enables array-arithmetic mode for a formula.' },
            { name: 'FILTER', syntax: 'FILTER(SourceArray, BoolArray1, BoolArray2, ...BoolArrayN)', description: 'Filters an array based on one or more boolean conditions.' },
            { name: 'ARRAY_CONSTRAIN', syntax: 'ARRAY_CONSTRAIN(Array, Height, Width)', description: 'Truncates an array to the given dimensions.' },
        ],
    },
]
