export interface UniwindSource {
    packageName: string
    packageDir: string // resolved real path
}

export function buildUniwindSources(sources: UniwindSource[]): string {
    const lines = [
        '/* Auto-generated by app/scripts/generate.ts — do not edit. */',
        '/* Regenerated on every generate run. */',
    ]
    for (const { packageName, packageDir } of sources) {
        lines.push(`@source "${packageDir}";  /* ${packageName} */`)
    }
    return `${lines.join('\n')}\n`
}
