import * as fs from 'node:fs'
import * as path from 'node:path'

export interface ServerPkg {
    slug: string
    module: string
    serverRelPath: string // relative to SERVER_DIR
}

function slugToIdentifier(slug: string): string {
    return slug.replace(/-([a-z])/g, (_m, c) => c.toUpperCase())
}

export function buildPackageExtensionsGo(pkgs: ServerPkg[]): string {
    if (pkgs.length === 0) {
        return [
            '// Code generated by app/scripts/generate.ts. DO NOT EDIT.',
            'package main',
            '',
            'import "github.com/pocketbase/pocketbase"',
            '',
            'func registerPackageExtensions(_ *pocketbase.PocketBase) {}',
            '',
        ].join('\n')
    }
    const imports = pkgs.map(p => `\t${slugToIdentifier(p.slug)} "${p.module}"`)
    const calls = pkgs.map(p => `\t${slugToIdentifier(p.slug)}.Register(app)`)
    return [
        '// Code generated by app/scripts/generate.ts. DO NOT EDIT.',
        'package main',
        '',
        'import (',
        '\t"github.com/pocketbase/pocketbase"',
        ...imports,
        ')',
        '',
        'func registerPackageExtensions(app *pocketbase.PocketBase) {',
        ...calls,
        '}',
        '',
    ].join('\n')
}

export function buildGoWork(coreRelPath: string, pkgs: ServerPkg[]): string {
    const uses = pkgs.map(p => `    ${p.serverRelPath}`)
    return [
        'go 1.25.0',
        '',
        'use (',
        '    .',
        `    ${coreRelPath}`,
        ...uses,
        ')',
        '',
    ].join('\n')
}

// Replace (or create) a symlink at linkPath → target.
export function replaceSymlink(target: string, linkPath: string) {
    try {
        // lstatSync (not existsSync) so a BROKEN existing symlink is still
        // detected and removed; it throws ENOENT only when nothing is there.
        fs.lstatSync(linkPath)
        fs.unlinkSync(linkPath)
    } catch {
        // nothing at linkPath — nothing to remove
    }
    fs.mkdirSync(path.dirname(linkPath), { recursive: true })
    fs.symlinkSync(target, linkPath)
}
