export interface Frontmatter {
    title: string
    summary: string
    tags: string[]
    order: number | null
    body: string
}

// Minimal YAML frontmatter parser for help docs (title/summary/tags/order).
export function parseFrontmatter(raw: string): Frontmatter {
    const match = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/)
    if (!match) {
        return { title: '', summary: '', tags: [], order: null, body: raw }
    }
    const [, head, body] = match
    let title = ''
    let summary = ''
    let tags: string[] = []
    let order: number | null = null
    for (const line of head.split('\n')) {
        const kv = line.match(/^(\w+):\s*(.*)$/)
        if (!kv) continue
        const [, key, valRaw] = kv
        const val = valRaw.trim()
        if (key === 'title') title = stripQuotes(val)
        else if (key === 'summary') summary = stripQuotes(val)
        else if (key === 'order') order = val === '' ? null : Number(val)
        else if (key === 'tags') tags = parseInlineArray(val)
    }
    return { title, summary, tags, order, body }
}

function stripQuotes(s: string): string {
    return s.replace(/^["']|["']$/g, '')
}

// Parse `[a, "b c", d]` → ['a','b c','d'].
function parseInlineArray(s: string): string[] {
    const inner = s.replace(/^\[|\]$/g, '').trim()
    if (!inner) return []
    return inner
        .split(',')
        .map(t => stripQuotes(t.trim()))
        .filter(Boolean)
}

export interface HelpTopicInput {
    topicId: string
    frontmatter: Frontmatter
}
export interface HelpGroupInput {
    packageName: string
    pkgSlug: string
    topics: HelpTopicInput[]
}

export function buildHelpSource(groups: HelpGroupInput[]): string {
    const lines: string[] = [
        '// Auto-generated by app/scripts/generate.ts — do not edit',
        '',
        'export interface HelpTopicEntry {',
        '    id: string',
        '    pkgSlug: string',
        '    topicId: string',
        '    title: string',
        '    summary: string',
        '    tags: string[]',
        '    body: string',
        '}',
        '',
        'export interface HelpGroup {',
        '    packageName: string',
        '    pkgSlug: string',
        '    topics: HelpTopicEntry[]',
        '}',
        '',
        'export const packageHelp: HelpGroup[] = [',
    ]
    for (const g of groups) {
        const sorted = [...g.topics].sort((a, b) => {
            const ao = a.frontmatter.order
            const bo = b.frontmatter.order
            if (ao != null && bo != null) return ao - bo
            if (ao != null) return -1
            if (bo != null) return 1
            return a.topicId.localeCompare(b.topicId)
        })
        lines.push('    {')
        lines.push(`        packageName: ${JSON.stringify(g.packageName)},`)
        lines.push(`        pkgSlug: ${JSON.stringify(g.pkgSlug)},`)
        lines.push('        topics: [')
        for (const t of sorted) {
            const entry = {
                id: `${g.pkgSlug}:${t.topicId}`,
                pkgSlug: g.pkgSlug,
                topicId: t.topicId,
                title: t.frontmatter.title,
                summary: t.frontmatter.summary,
                tags: t.frontmatter.tags,
                body: t.frontmatter.body,
            }
            lines.push(`            ${JSON.stringify(entry)},`)
        }
        lines.push('        ],')
        lines.push('    },')
    }
    lines.push(']')
    lines.push('')
    return lines.join('\n')
}
