export interface ConfigSettingsPanel {
    slug: string
    label: string
    component: string // subpath e.g. 'settings/provider'
}

export interface ConfigPkg {
    packageName: string
    slug: string
    schemaType: string // e.g. 'ContactsSchema'; '' for settings-only (must be non-empty when hasRegister is true)
    hasRegister: boolean
    hasSidebar: boolean
    hasProvider: boolean
    hasSeed: boolean
    settings: ConfigSettingsPanel[]
    manifest: { name: string; slug: string; version: string; description: string } & Record<
        string,
        unknown
    >
}

function ident(slug: string): string {
    return slug.replace(/-([a-z])/g, (_m, c) => c.toUpperCase())
}

function jsonLiteral(value: unknown): string {
    return JSON.stringify(value)
}

export function buildConfigSource(pkgs: ConfigPkg[]): string {
    for (const p of pkgs) {
        if (p.hasRegister && !p.schemaType) {
            throw new Error(
                `ConfigPkg for '${p.packageName}': hasRegister is true but schemaType is empty`
            )
        }
    }
    const lines: string[] = ['// Auto-generated by app/scripts/generate.ts — do not edit']
    lines.push("import { definePackageEntry } from '@tinycld/core/lib/packages/config-types'")

    const needsLazy = pkgs.some(p => p.hasSidebar || p.settings.length > 0)
    if (needsLazy) lines.push("import { lazy } from 'react'")

    for (const p of pkgs) {
        if (p.hasRegister) {
            lines.push(
                `import { registerCollections as ${ident(p.slug)}Register } from '${p.packageName}/collections'`
            )
            lines.push(`import type { ${p.schemaType} } from '${p.packageName}/types'`)
        }
        if (p.hasProvider) {
            lines.push(`import ${ident(p.slug)}Provider from '${p.packageName}/provider'`)
        }
    }

    lines.push('')
    lines.push('export const tinycldConfig = [')
    for (const p of pkgs) {
        const schemaParam = p.hasRegister ? p.schemaType : 'Record<string, never>'
        lines.push(`    definePackageEntry<${schemaParam}>()({`)
        lines.push(
            `        manifest: { ...(${jsonLiteral(p.manifest)} as const), packageName: ${jsonLiteral(p.packageName)} },`
        )
        if (p.hasRegister) lines.push(`        registerCollections: ${ident(p.slug)}Register,`)
        if (p.hasSidebar) {
            lines.push(`        sidebar: lazy(() => import('${p.packageName}/sidebar')),`)
        }
        if (p.hasProvider) lines.push(`        provider: ${ident(p.slug)}Provider,`)
        if (p.settings.length > 0) {
            lines.push('        settings: [')
            for (const s of p.settings) {
                lines.push(
                    `            { slug: ${jsonLiteral(s.slug)}, label: ${jsonLiteral(s.label)}, Component: lazy(() => import('${p.packageName}/${s.component}')) },`
                )
            }
            lines.push('        ],')
        }
        lines.push('    }),')
    }
    lines.push('] as const')
    lines.push('')

    const schemaTypes = pkgs.filter(p => p.hasRegister).map(p => p.schemaType)
    const merged = schemaTypes.length > 0 ? schemaTypes.join(' & ') : 'Record<string, never>'
    lines.push(`export type MergedPackageSchema = ${merged}`)
    lines.push('')
    return lines.join('\n')
}

export function buildSeedsSource(pkgs: ConfigPkg[]): string {
    const withSeeds = pkgs.filter(p => p.hasSeed)
    const lines: string[] = ['// Auto-generated by app/scripts/generate.ts — do not edit']
    for (const p of withSeeds) {
        lines.push(`import ${ident(p.slug)}Seed from '${p.packageName}/seed'`)
    }
    lines.push('')
    lines.push('export const tinycldSeeds = [')
    for (const p of withSeeds) {
        const deps = (p.manifest.dependencies as string[] | undefined) ?? []
        const depsLiteral = deps.length > 0 ? jsonLiteral(deps) : '[]'
        lines.push(
            `    { manifest: { slug: ${jsonLiteral(p.slug)}, dependencies: ${depsLiteral} }, seed: ${ident(p.slug)}Seed },`
        )
    }
    lines.push('] as const')
    lines.push('')
    return lines.join('\n')
}
